services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Node44_youtube
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
